version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\gnode\gogs
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.11

build: false
deploy: false

install:
  - go build -v

notifications:
  - provider: Email
    to:
      - dev@g-node.org
    on_build_success: false
